### ISSUE TITLE
Feature requests:

### ISSUE THREAD

**Issue by AuroraHydroid** [eszesbalint/eszesbalint.github.io#1]
Thank you for this excellent tool! It makes a huge difference in how I'm able to use display entities.

I have some feature suggestions:

-Mirror selection
-Pick save name and save location (currently saves under a generic name in my downloads)
-Don't include non-block entities (like beds, signs and item frames) since they don't render, or allow them to render
-Undo/redo or some sort (please)

**Comment by eszesbalint** [comment]
Thank you for your suggestions!

I tried to address most of your suggestions in an upcoming version I'm releasing this weekend:
- There's no easy way to mirror block display entities in Minecraft. The most obvious solution would be to just set the scale to a negative value along a selected axis, but unfortunately that doesn't work in-game, as it doesn't render properly.  But I'm thinking about a workaround.
- Now you can name your project, and the downloaded file will have the same name.
- The editor will now alert the user if it can't load a block model. I will try to come up with a better solution.
- Added Undo / Redo functionality.

I created a separate repo for Block Display Studio. Future issues and suggestions should go there.
[https://github.com/eszesbalint/bdstudio](https://github.com/eszesbalint/bdstudio)
